AllCops:
  NewCops: enable

Metrics/AbcSize:
  Enabled: False

# Configuration parameters: AllowedMethods, AllowedPatterns.
Metrics/CyclomaticComplexity:
  Enabled: False

# Configuration parameters: CountComments, CountAsOne, AllowedMethods, AllowedPatterns.
Metrics/MethodLength:
  Enabled: False

# Configuration parameters: AllowedMethods, AllowedPatterns.
Metrics/PerceivedComplexity:
  Enabled: False

#
Naming/MethodName:
  AllowedPatterns: ["A_star"]
  Exclude:
    - "utils.rb"

# Configuration parameters: MinNameLength, AllowNamesEndingInNumbers, AllowedNames, ForbiddenNames.
# AllowedNames: as, at, by, cc, db, id, if, in, io, ip, of, on, os, pp, to
Naming/MethodParameterName:
  AllowedNames: ["n"]
  Exclude:
    - "utils.rb"

# Configuration parameters: EnforcedStyle, AllowedIdentifiers, AllowedPatterns.
# SupportedStyles: snake_case, camelCase
Naming/VariableName:
  AllowedIdentifiers: ["regA", "regB", "regC"]

Style/ClassVars:
  Enabled: False

Style/GlobalVars:
  Enabled: False

Lint/AmbiguousOperatorPrecedence:
  Enabled: False
